server :
  port : 2222
  
spring :
  cloud :
    config :
      server :
        git :
         uri : https://github.com/sandyachoppara/ConfigServer
         clone-on-start : true
         
          